# settings.json
# make sure choose Environment

###

# 1. user register
POST {{host}}/v1/users
content-type: application/json

{
  "name": "test",
  "password": "1234"
}


###

# 2. user login
POST {{host}}/v1/login
content-type: application/json

{
  "name": "test",
  "password": "1234"
}

###

# 3. get login user info by token
GET {{host}}/v1/owner
Authorization: Bearer {{token}}

###


