
# settings.json
# make sure choose Environment



# 创建文章
POST {{host}}/v1/post
Authorization: Bearer {{token}}
content-type: application/json

{
  "content": "苯（Benzene），是一种有机化合物，是最简单的芳烃，化学式是C6H6，在常温下是甜味、可燃、有致癌毒性的无色透明液体，并带有强烈的芳香气味。 它难溶于水，易溶于有机溶剂，本身也可作为有机溶剂。 苯具有的环系叫苯环，苯环去掉一个氢原子以后的结构叫苯基，用Ph表示，因此苯的化学式也可写作PhH。"
}

###

# 获取文章详细内容
GET {{host}}/v1/post/106
content-type: application/json


###

# 更新文章
PUT {{host}}/v1/post/1
Authorization: Bearer {{token}}
content-type: application/json

{
  "title": "可选",
  "content": "可选"
}

###

# 获取文章列表
GET {{host}}/v1/posts?page=1&per_page=1
content-type: application/json



###


