
# @host = https://api.cemcoe.com
@host = http://localhost:3001
# api index
GET {{host}}/

###

# 获取用户列表
GET {{host}}/v1/users

###

# 用户登录
POST {{host}}/v1/login
content-type: application/json

{
  "name": "cemcoe",
  "password": "1234"
}