
# settings.json
# make sure choose Environment

###

# 获取用户列表
GET {{host}}/v1/users

###

# 获取用户详情
GET {{host}}/v1/users/101
content-type: application/json

###

# 获取用户文章列表
GET {{host}}/v1/users/106/posts
content-type: application/json

###

# 获取用户SBT
GET {{host}}/v1/address/sbts
content-type: application/json




