const response = {
  result: "OK",
  data: {
    id: "m88479087694",
    seller: {
      id: 374690639,
      name: "♥パル♥",
      photo_url: "https://static.mercdn.net/members/374690639.jpg?1598953638",
      photo_thumbnail_url:
        "https://static.mercdn.net/thumb/members/374690639.jpg?1598953638",
      register_sms_confirmation: "yes",
      register_sms_confirmation_at: "2021-11-04 22:35:24",
      created: 1575293117,
      num_sell_items: 982,
      ratings: {
        good: 627,
        normal: 0,
        bad: 3,
      },
      num_ratings: 630,
      score: 624,
      is_official: false,
      quick_shipper: false,
      star_rating_score: 5,
    },
    status: "on_sale",
    name: "新品！喜平 プラチナ シルバー チェーン ネックレス Pt コート ユニセックス",
    price: 5899,
    description:
      "新品！喜平 プラチナ シルバー チェーン ネックレス Pt コート ユニセックス メンズ レディース ジュエリー 銀\r\n\r\n\r\n【 サイズ】\r\n約55cm\r\n\r\n太さ\r\n約 0.4cm\r\n\r\n重さ\r\n約7ｇ\r\n\r\n【 カラー】\r\nシルバー\r\n\r\n【 素材】\r\nPt900 プラチナ\r\nメッキコーティング\r\n\r\n\r\n※注意事項※\r\n・出品しております商品は、全て海外製品でございます。\r\n・クオリティや状態に個体差がある場合がございますので予めご了承くださいませ。\r\n・検品は常に行なっておりますが、商品が到着した際に万が一故障していたなどのトラブルがありましたら真摯にご対応させていただきますので必ず受け取り評価前にご連絡をお願いたします。\r\n・気になることや説明文に記載がない事項に関しましては、ご購入前にコメントにてご質問くださいませ。\r\n・説明文や画像に記載のある状態に関する事由や、サイズ感の違いなど購入者様のご都合による返品やクレームはご対応できかねます。\r\n・すべての商品に実物写真を追加しておりますので、気になる方は事前にご確認くださいませ。\r\n・同梱割引はご購入前にお申し付けいただければ可能でございますが、ご購入後は価格変更できないので価格はそのままでのお取引となります。\r\n・私本人の着画は行なっておりませんので、予めご了承くださいませ。\r\n・ご希望配達日時がある場合は、必ずご購入前にご連絡くださいませ。（購入後即日〜2日以内に発送いたします）\r\n\r\n\r\nY349",
    photos: [
      "https://static.mercdn.net/item/detail/orig/photos/m88479087694_1.jpg?1678194266",
      "https://static.mercdn.net/item/detail/orig/photos/m88479087694_2.jpg?1678194266",
      "https://static.mercdn.net/item/detail/orig/photos/m88479087694_3.jpg?1678194266",
      "https://static.mercdn.net/item/detail/orig/photos/m88479087694_4.jpg?1678194266",
    ],
    photo_paths: [
      "photos/m88479087694_1.jpg",
      "photos/m88479087694_2.jpg",
      "photos/m88479087694_3.jpg",
      "photos/m88479087694_4.jpg",
    ],
    thumbnails: [
      "https://static.mercdn.net/c!/w=240/thumb/photos/m88479087694_1.jpg?1678194266",
    ],
    item_category: {
      id: 226,
      name: "ネックレス",
      display_order: 50,
      parent_category_id: 21,
      parent_category_name: "アクセサリー",
      root_category_id: 1,
      root_category_name: "レディース",
      brand_group_id: 1,
    },
    item_condition: {
      id: 1,
      name: "新品、未使用",
    },
    colors: [],
    shipping_payer: {
      id: 2,
      name: "送料込み(出品者負担)",
      code: "seller",
    },
    shipping_method: {
      id: 17,
      name: "ゆうゆうメルカリ便",
      is_deprecated: "no",
    },
    shipping_from_area: {
      id: 40,
      name: "福岡県",
    },
    shipping_duration: {
      id: 1,
      name: "1~2日で発送",
      min_days: 1,
      max_days: 2,
    },
    shipping_class: {
      id: 0,
      fee: 0,
      icon_id: 0,
      pickup_fee: 0,
      shipping_fee: 0,
      total_fee: 0,
      is_pickup: false,
    },
    num_likes: 3,
    num_comments: 0,
    comments: [],
    updated: 1679033300,
    created: 1678194266,
    pager_id: 5455048781,
    liked: false,
    checksum: "c6ac0ae56d6dfbb8e36eab4a343f6592",
    is_dynamic_shipping_fee: false,
    application_attributes: {},
    is_shop_item: "no",
    hash_tags: [],
    is_anonymous_shipping: true,
    is_web_visible: true,
    is_offerable: false,
    is_organizational_user: false,
    organizational_user_status: "",
    is_stock_item: false,
    is_cancelable: true,
    shipped_by_worker: false,
    additional_services: [],
    has_additional_service: false,
    delivery_facility_type: "japan_post",
    has_like_list: false,
    is_offerable_v2: false,
    is_dismissed: false,
  },
  meta: {},
};

export { response };
